### ISSUE TITLE
More Stereoisomer grading failures

### ISSUE THREAD

**Issue by MrDarkHorse** [partridgejiang/Kekule.js#104]
I've been trying to carefully illustrate the different classes of use cases I'm seeing.

<img width="566" alt="screen shot 2019-01-18 at 12 36 22 pm" src="https://user-images.githubusercontent.com/9271182/51406415-af911300-1b1e-11e9-8ce4-81646ab3453a.png">
<img width="564" alt="screen shot 2019-01-18 at 12 38 35 pm" src="https://user-images.githubusercontent.com/9271182/51406416-af911300-1b1e-11e9-9b1b-4f89a2786079.png">
<img width="538" alt="screen shot 2019-01-18 at 12 39 16 pm" src="https://user-images.githubusercontent.com/9271182/51406417-af911300-1b1e-11e9-8ad5-d7bcc99b71e5.png">
<img width="552" alt="screen shot 2019-01-18 at 12 39 39 pm" src="https://user-images.githubusercontent.com/9271182/51406418-b029a980-1b1e-11e9-90ad-6edaf4caede7.png">
<img width="557" alt="screen shot 2019-01-18 at 12 40 00 pm" src="https://user-images.githubusercontent.com/9271182/51406419-b029a980-1b1e-11e9-910a-af9e9552889f.png">
<img width="553" alt="screen shot 2019-01-18 at 12 40 37 pm" src="https://user-images.githubusercontent.com/9271182/51406420-b029a980-1b1e-11e9-8295-9c09714ad475.png">

**Comment by MrDarkHorse** [comment]
All of the above I was able to reproduce on the Structure Comparison demo page: 
 http://partridgejiang.github.io/Kekule.js/demos/demoLauncher.html?id=structCompare

But I get even weirder results if I run the structure compare tool directly from the master branch.

**Comment by MrDarkHorse** [comment]
<img width="1239" alt="screen shot 2019-01-18 at 1 04 35 pm" src="https://user-images.githubusercontent.com/9271182/51407639-17952880-1b22-11e9-86d1-526c32119cbf.png">
<img width="1216" alt="screen shot 2019-01-18 at 1 04 49 pm" src="https://user-images.githubusercontent.com/9271182/51407640-17952880-1b22-11e9-89ff-ab6900051a47.png">
<img width="1215" alt="screen shot 2019-01-18 at 1 03 29 pm" src="https://user-images.githubusercontent.com/9271182/51407642-17952880-1b22-11e9-8926-4bb811bf3165.png">
<img width="1224" alt="screen shot 2019-01-18 at 1 03 42 pm" src="https://user-images.githubusercontent.com/9271182/51407644-182dbf00-1b22-11e9-90dc-0310bd4cdba4.png">
<img width="1252" alt="screen shot 2019-01-18 at 1 06 33 pm" src="https://user-images.githubusercontent.com/9271182/51407645-182dbf00-1b22-11e9-985c-5a33da7daa6f.png">
<img width="1241" alt="screen shot 2019-01-18 at 1 06 50 pm" src="https://user-images.githubusercontent.com/9271182/51407646-182dbf00-1b22-11e9-8f07-9aae1ad7f462.png">

**Comment by partridgejiang** [comment]
Hi @MrDarkHorse, the demo pages had not been updated for a while, and I have just updated them with the latest js files. You may check again now, :).

**Comment by MrDarkHorse** [comment]
Okay, I agree that updating the demo page now makes the master branch and the demo page act consistently.  Unfortunately, most of these things are still an issue.

<img width="728" alt="screen shot 2019-01-23 at 11 49 30 am" src="https://user-images.githubusercontent.com/9271182/51626739-d926b180-1f05-11e9-8ed6-636cbae74b49.png">
<img width="746" alt="screen shot 2019-01-23 at 11 49 49 am" src="https://user-images.githubusercontent.com/9271182/51626740-d9bf4800-1f05-11e9-827e-7d3834994985.png">
<img width="699" alt="screen shot 2019-01-23 at 11 50 26 am" src="https://user-images.githubusercontent.com/9271182/51626741-d9bf4800-1f05-11e9-9ebf-4e779eedffdf.png">
<img width="683" alt="screen shot 2019-01-23 at 11 50 47 am" src="https://user-images.githubusercontent.com/9271182/51626742-d9bf4800-1f05-11e9-929e-e8e9e87c941e.png">
<img width="689" alt="screen shot 2019-01-23 at 11 51 00 am" src="https://user-images.githubusercontent.com/9271182/51626743-d9bf4800-1f05-11e9-8514-6e844f61e995.png">
<img width="724" alt="screen shot 2019-01-23 at 11 53 28 am" src="https://user-images.githubusercontent.com/9271182/51626744-d9bf4800-1f05-11e9-9c02-d9d6dcc361fc.png">
<img width="669" alt="screen shot 2019-01-23 at 11 53 50 am" src="https://user-images.githubusercontent.com/9271182/51626750-e04dbf80-1f05-11e9-83b7-831ab50d6487.png">
<img width="649" alt="screen shot 2019-01-23 at 11 54 31 am" src="https://user-images.githubusercontent.com/9271182/51626751-e04dbf80-1f05-11e9-8430-ede6a4c8a98e.png">
<img width="671" alt="screen shot 2019-01-23 at 11 54 50 am" src="https://user-images.githubusercontent.com/9271182/51626752-e04dbf80-1f05-11e9-8bb1-65091a127b0e.png">

**Comment by partridgejiang** [comment]
Hi @MrDarkHorse, when two groups are on the same side of double bond (anyway, it is not a proper situation for a double bond), the current comparison approach is something like the following figure:

![image](https://user-images.githubusercontent.com/10516825/51686014-7e3aaa80-202a-11e9-8d39-f7728c4d3e79.png)

The rotation angles of the two groups to the double bond are compared. In that figure above, the two structures are regarded as same. So be the other test cases.

**Comment by MrDarkHorse** [comment]
I agree that these are "improper" situations for a double bond.  We are trying to use this to help teach people how structures work, so we have to give the user freedom to be wrong so that we can give them feedback.

Situations like these are weird, but also lead to false positives in the compare tool.

**Comment by partridgejiang** [comment]
Eh... that is to say, the improper double bonds should always be regarded as wrong and be different to proper ones in your requirement, e.g.:
![image](https://user-images.githubusercontent.com/10516825/51747784-77bd3900-20e5-11e9-87c0-c962d9c51a94.png) vs. ![image](https://user-images.githubusercontent.com/10516825/51747815-83106480-20e5-11e9-8cb6-a40ec89cdbd4.png) : Different

![image](https://user-images.githubusercontent.com/10516825/51747856-9de2d900-20e5-11e9-94eb-844521e44797.png) vs. ![image](https://user-images.githubusercontent.com/10516825/51747815-83106480-20e5-11e9-8cb6-a40ec89cdbd4.png)  : Different too

If so, I can soon start to implement this feature by adding an additional flag to comparison process.

**Comment by MrDarkHorse** [comment]
Yes.  In my opinion both of those cases should be considered different.  One is a little bit wrong, and one is VERY wrong.  Haha.  :)

**Comment by partridgejiang** [comment]
Hi @MrDarkHorse , a new commit has been made, please check the latest dist files. The previous improper cases will be regarded as different structure when comparing molecule structures with an additional option flag:
```js
var isSame = mol1.equalStructure(mol2, {strictStereoBondGeometry: true});
```

**Comment by MrDarkHorse** [comment]
Awesome!  Taking a look now.

**Comment by MrDarkHorse** [comment]
Well, I'm not sure if I'm doing something wrong, but this still isn't working for me.

<img width="671" alt="screen shot 2019-01-23 at 11 54 50 am" src="https://user-images.githubusercontent.com/9271182/51924224-3dd48700-23b2-11e9-81c8-1cfed409286c.png">

**Comment by partridgejiang** [comment]
Eh... maybe some files are not updated well when branches being merged? I have updated the release files again, and modified the structure comparison demo a little (with an extra options panel where you can toggle strictStereoBondGeometry in the UI now). Things should be OK now.

**Comment by MrDarkHorse** [comment]
Working now!  Turns out, in addition to needing the structureCompare updates to include the change, in my code I was running an additional standardize function and not passing the "options" in, so the strict setting was being lost.
