### ISSUE TITLE
Matching issue: rotation about a single bond, bicyclic isomer

### ISSUE THREAD

**Issue by MrDarkHorse** [partridgejiang/Kekule.js#107]
This one is a strange failure.

<img width="739" alt="screen shot 2019-01-23 at 3 00 53 pm" src="https://user-images.githubusercontent.com/9271182/51636827-cfaa4300-1f1f-11e9-8609-8a4cfdce1043.png">

**Comment by MrDarkHorse** [comment]
`{"coordPos2D":0,"coordPos3D":0,"defAutoScaleRefLength":0.8,"root":{"id":"o1","coordPos2D":0,"coordPos3D":0,"children":{"id":"o2","coordPos2D":0,"coordPos3D":0,"items":[{"__type__":"Kekule.Molecule","id":"m1","coordPos2D":0,"coordPos3D":0,"renderOptions":{"expanded":true,"__type__":"object"},"coord2D":{"x":-0.2227067360350481,"y":2.527783862723622,"__type__":"object"},"charge":0,"parity":null,"ctab":{"nodes":[{"__type__":"Kekule.Atom","id":"a1","coordPos2D":0,"coordPos3D":0,"coord2D":{"x":8.881784197001252e-16,"y":-0.4618802153517003,"__type__":"object"},"charge":0,"parity":null,"isotopeId":"C"},{"__type__":"Kekule.Atom","id":"a2","coordPos2D":0,"coordPos3D":0,"coord2D":{"x":0.4000000000000008,"y":0.23094010767585038,"__type__":"object"},"charge":0,"parity":null,"isotopeId":"C"},{"__type__":"Kekule.Atom","id":"a3","coordPos2D":0,"coordPos3D":0,"coord2D":{"x":-0.39999999999999947,"y":0.23094010767585038,"__type__":"object"},"charge":0,"parity":null,"isotopeId":"C"},{"__type__":"Kekule.Atom","id":"a4","coordPos2D":0,"coordPos3D":0,"coord2D":{"x":1.0928203230275524,"y":0.6309401076758503,"__type__":"object"},"charge":0,"parity":null,"isotopeId":"C"},{"__type__":"Kekule.Atom","id":"a5","coordPos2D":0,"coordPos3D":0,"coord2D":{"x":1.785640646055103,"y":0.2309401076758495,"__type__":"object"},"charge":0,"parity":null,"isotopeId":"C"},{"__type__":"Kekule.Atom","id":"a6","coordPos2D":0,"coordPos3D":0,"coord2D":{"x":2.4784609690826547,"y":0.6309401076758494,"__type__":"object"},"charge":0,"parity":null,"isotopeId":"C"},{"__type__":"Kekule.Atom","id":"a8","coordPos2D":0,"coordPos3D":0,"coord2D":{"x":3.2784609690826563,"y":0.6309401076758503,"__type__":"object"},"charge":0,"parity":null,"isotopeId":"C"},{"__type__":"Kekule.Atom","id":"a9","coordPos2D":0,"coordPos3D":0,"coord2D":{"x":2.8784609690826577,"y":1.323760430703401,"__type__":"object"},"charge":0,"parity":null,"isotopeId":"C"}],"anchorNodes":[],"connectors":[{"__type__":"Kekule.Bond","id":"b1","coordPos2D":0,"coordPos3D":0,"parity":null,"bondType":"covalent","bondOrder":1,"electronCount":2,"isInAromaticRing":false,"connectedObjs":[0,1]},{"__type__":"Kekule.Bond","id":"b2","coordPos2D":0,"coordPos3D":0,"parity":null,"bondType":"covalent","bondOrder":1,"electronCount":2,"isInAromaticRing":false,"connectedObjs":[1,2]},{"__type__":"Kekule.Bond","id":"b3","coordPos2D":0,"coordPos3D":0,"parity":null,"bondType":"covalent","bondOrder":1,"electronCount":2,"isInAromaticRing":false,"connectedObjs":[2,0]},{"__type__":"Kekule.Bond","id":"b4","coordPos2D":0,"coordPos3D":0,"parity":null,"bondType":"covalent","bondOrder":1,"electronCount":2,"isInAromaticRing":false,"connectedObjs":[1,3]},{"__type__":"Kekule.Bond","id":"b5","coordPos2D":0,"coordPos3D":0,"parity":null,"bondType":"covalent","bondOrder":1,"electronCount":2,"isInAromaticRing":false,"connectedObjs":[3,4]},{"__type__":"Kekule.Bond","id":"b6","coordPos2D":0,"coordPos3D":0,"parity":null,"bondType":"covalent","bondOrder":1,"electronCount":2,"isInAromaticRing":false,"connectedObjs":[4,5]},{"__type__":"Kekule.Bond","id":"b7","coordPos2D":0,"coordPos3D":0,"parity":null,"bondType":"covalent","bondOrder":1,"electronCount":2,"isInAromaticRing":false,"connectedObjs":[5,6]},{"__type__":"Kekule.Bond","id":"b8","coordPos2D":0,"coordPos3D":0,"parity":null,"bondType":"covalent","bondOrder":1,"electronCount":2,"isInAromaticRing":false,"connectedObjs":[6,7]},{"__type__":"Kekule.Bond","id":"b9","coordPos2D":0,"coordPos3D":0,"parity":null,"bondType":"covalent","bondOrder":1,"electronCount":2,"isInAromaticRing":false,"connectedObjs":[7,5]}],"__type__":"Kekule.StructureConnectionTable"}}],"__type__":"Kekule.ChemObjList"},"__type__":"Kekule.ChemSpaceElement"},"enableAutoId":true,"screenSize":{"x":1500,"y":1000,"__type__":"object"},"size2D":{"x":8.173493975903614,"y":3.35421686746988,"__type__":"object"},"__type__":"Kekule.ChemDocument"}`

**Comment by MrDarkHorse** [comment]
`{"coordPos2D":0,"coordPos3D":0,"defAutoScaleRefLength":0.8,"root":{"id":"o1","coordPos2D":0,"coordPos3D":0,"children":{"id":"o2","coordPos2D":0,"coordPos3D":0,"items":[{"__type__":"Kekule.Molecule","id":"m1","coordPos2D":0,"coordPos3D":0,"renderOptions":{"expanded":true,"__type__":"object"},"coord2D":{"x":-0.2227067360350481,"y":2.527783862723622,"__type__":"object"},"charge":0,"parity":null,"ctab":{"nodes":[{"__type__":"Kekule.Atom","id":"a1","coordPos2D":0,"coordPos3D":0,"coord2D":{"x":8.881784197001252e-16,"y":-0.4618802153517003,"__type__":"object"},"charge":0,"parity":null,"isotopeId":"C"},{"__type__":"Kekule.Atom","id":"a2","coordPos2D":0,"coordPos3D":0,"coord2D":{"x":0.4000000000000008,"y":0.23094010767585038,"__type__":"object"},"charge":0,"parity":null,"isotopeId":"C"},{"__type__":"Kekule.Atom","id":"a3","coordPos2D":0,"coordPos3D":0,"coord2D":{"x":-0.39999999999999947,"y":0.23094010767585038,"__type__":"object"},"charge":0,"parity":null,"isotopeId":"C"},{"__type__":"Kekule.Atom","id":"a4","coordPos2D":0,"coordPos3D":0,"coord2D":{"x":1.0928203230275524,"y":0.6309401076758503,"__type__":"object"},"charge":0,"parity":null,"isotopeId":"C"},{"__type__":"Kekule.Atom","id":"a5","coordPos2D":0,"coordPos3D":0,"coord2D":{"x":1.785640646055103,"y":0.2309401076758495,"__type__":"object"},"charge":0,"parity":null,"isotopeId":"C"},{"__type__":"Kekule.Atom","id":"a6","coordPos2D":0,"coordPos3D":0,"coord2D":{"x":2.4784609690826547,"y":0.6309401076758494,"__type__":"object"},"charge":0,"parity":null,"isotopeId":"C"},{"__type__":"Kekule.Atom","id":"a8","coordPos2D":0,"coordPos3D":0,"coord2D":{"x":2.489566755866154,"y":-0.19423559513539201,"__type__":"object"},"charge":0,"parity":null,"isotopeId":"C"},{"__type__":"Kekule.Atom","id":"a9","coordPos2D":0,"coordPos3D":0,"coord2D":{"x":3.2195982454608987,"y":0.21791660083848763,"__type__":"object"},"charge":0,"parity":null,"isotopeId":"C"}],"anchorNodes":[],"connectors":[{"__type__":"Kekule.Bond","id":"b1","coordPos2D":0,"coordPos3D":0,"parity":null,"bondType":"covalent","bondOrder":1,"electronCount":2,"isInAromaticRing":false,"connectedObjs":[0,1]},{"__type__":"Kekule.Bond","id":"b2","coordPos2D":0,"coordPos3D":0,"parity":null,"bondType":"covalent","bondOrder":1,"electronCount":2,"isInAromaticRing":false,"connectedObjs":[1,2]},{"__type__":"Kekule.Bond","id":"b3","coordPos2D":0,"coordPos3D":0,"parity":null,"bondType":"covalent","bondOrder":1,"electronCount":2,"isInAromaticRing":false,"connectedObjs":[2,0]},{"__type__":"Kekule.Bond","id":"b4","coordPos2D":0,"coordPos3D":0,"parity":null,"bondType":"covalent","bondOrder":1,"electronCount":2,"isInAromaticRing":false,"connectedObjs":[1,3]},{"__type__":"Kekule.Bond","id":"b5","coordPos2D":0,"coordPos3D":0,"parity":null,"bondType":"covalent","bondOrder":1,"electronCount":2,"isInAromaticRing":false,"connectedObjs":[3,4]},{"__type__":"Kekule.Bond","id":"b6","coordPos2D":0,"coordPos3D":0,"parity":null,"bondType":"covalent","bondOrder":1,"electronCount":2,"isInAromaticRing":false,"connectedObjs":[4,5]},{"__type__":"Kekule.Bond","id":"b7","coordPos2D":0,"coordPos3D":0,"parity":null,"bondType":"covalent","bondOrder":1,"electronCount":2,"isInAromaticRing":false,"connectedObjs":[5,6]},{"__type__":"Kekule.Bond","id":"b8","coordPos2D":0,"coordPos3D":0,"parity":null,"bondType":"covalent","bondOrder":1,"electronCount":2,"isInAromaticRing":false,"connectedObjs":[6,7]},{"__type__":"Kekule.Bond","id":"b9","coordPos2D":0,"coordPos3D":0,"parity":null,"bondType":"covalent","bondOrder":1,"electronCount":2,"isInAromaticRing":false,"connectedObjs":[7,5]}],"__type__":"Kekule.StructureConnectionTable"}}],"__type__":"Kekule.ChemObjList"},"__type__":"Kekule.ChemSpaceElement"},"enableAutoId":true,"screenSize":{"x":1500,"y":1000,"__type__":"object"},"size2D":{"x":8.173493975903614,"y":3.35421686746988,"__type__":"object"},"__type__":"Kekule.ChemDocument"}`

**Comment by partridgejiang** [comment]
Hi @MrDarkHorse, a new fix has been made, please check the latest commits. Thanks again for the valuable feedback.
