### ISSUE TITLE
Wedge/Dash direction matching behavior 

### ISSUE THREAD

**Issue by MrDarkHorse** [partridgejiang/Kekule.js#111]
This may be a difference in convention.  The strong preference from the folks I'm working with is that wedge direction should be enforced in the matcher, and that dash is the one that can be ambiguous.  It looks like, however, the current behavior in Kekule is the exact reverse.

Wedge is allowed to be either direction and dash enforces direction.

Is this maybe configurable?

![screen shot 2019-02-04 at 10 58 12 am](https://user-images.githubusercontent.com/9271182/52224059-b2a13880-286c-11e9-9bba-5fe43a5ec5cd.png)
![screen shot 2019-02-04 at 10 57 56 am](https://user-images.githubusercontent.com/9271182/52224061-b2a13880-286c-11e9-99ca-7c2d1b21e207.png)

**Comment by MrDarkHorse** [comment]
Any thoughts on this?

**Comment by partridgejiang** [comment]
Hi @MrDarkHorse, the code has now been modified to make the wedge bonds as the prior factors in stereo perception. Please check the latest commit. However, if the old behavior is needed, you can always pass option parameter {wedgeBondPrior: false} in the perception process.

**Comment by MrDarkHorse** [comment]
Awesome!  Thanks!
