### ISSUE TITLE
question on 3d structure

### ISSUE THREAD

**Issue by sylvaincordiere** [partridgejiang/Kekule.js#117]
Hi partridgejiang
I discover kekele.js today and I find it amazing specially the 3d structure [generator](http://partridgejiang.github.io/Kekule.js/demos/demoLauncher.html?id=openBabelGen3D).
I just want to know what algorithm do you use to generate the 3D structure ?
Thanks

**Comment by partridgejiang** [comment]
Hi @sylvaincordiere, actually, the 3D structure calculation is not performed by Kekule.js itself, but with the [OpenBabel](http://openbabel.org), a famous chemoinformatics toolkit written in C++.  With the help of [Emscripten](https://emscripten.org/), the lib was compiled into JavaScript. Kekule.js provides a adapter for the compiled OpenBabel lib, thus in the 3D generator demo, all MM calculations can be done totally in the browser environment.
