### ISSUE TITLE
ring button is empty 

### ISSUE THREAD

**Issue by trinhsk** [partridgejiang/Kekule.js#121]
Hi, I'm new to Kekule.js. I'm trying to produce a chem composer.

` var composer = new Kekule.Editor.Composer(document.getElementById('kekulecomposer'));
            composer
              .setEnableCreateNewDoc(false)
              .setEnableLoadNewFile(false)
              .setAllowCreateNewChild(false)
              .setChemToolButtons(['manipulate', 'erase', 'bond', 'atom', 'formula', 'ring', 'charge']);
`

The output looks just like in the documentation; however the ring button and arrow button is empty. I can only make one type of arrow and one type of ring (3-member). I don't see the different types like in the exmample from: [http://partridgejiang.github.io/Kekule.js/documents/tutorial/examples/chemViewer.html]

thanks for your time.

**Comment by partridgejiang** [comment]
Hi @trinhsk, the initial width of composer element is rather small (defaultly 550px) and is not suffcient to display the whole ring or arrow sub toolbar. To solve the problem, just apply a CSS style (e.g. width: 700px) to the 'kekulecomposer' element before creating composer instance. Enjoy, :).

**Comment by trinhsk** [comment]
Great! thank you so much. I love easy fixes :)
