### ISSUE TITLE
Export/copy  to image formats

### ISSUE THREAD

**Issue by Catastrophi** [partridgejiang/Kekule.js#126]
Will there be an option to export/copy the canvans contents to image formats?

**Comment by partridgejiang** [comment]
Perhaps the function you need is method exportToDataUri provided by the viewer or editor widget? For example:
```js
var dataUri = viewer.exportToDataUri();
// var dataUri = composer.getEditor().exportToDataUri();
document.getElementById('img1').src = dataUri;
```
