### ISSUE TITLE
Deleting curved arrows in composer issue.

### ISSUE THREAD

**Issue by cleblond** [partridgejiang/Kekule.js#128]
When I delete a curved arrow (electronPushingArrow) in the editor by using the eraser button the curved arrow is not removed from the exported kekule-json.  If however you select the curved arrow first and then click the eraser button, the curved arrow is removed from the json that is exported.

**Comment by partridgejiang** [comment]
Thanks a lot for the feedback. However, I can not reproduction this bug in my environment. Would you please provide more details of it (e.g., the exported JSON before and after erasing the arrow)?

**Comment by cleblond** [comment]
Sorry I can not reproduce now either.
