### ISSUE TITLE
[RESOLVED] Strange ring behavior when disabling operation history

### ISSUE THREAD

**Issue by antonintlh** [partridgejiang/Kekule.js#131]
Hello!

I found a strange behavior on rings when disabling operation history.

I use `setEnableOperHistory(false)`.
```javascript
const composer = new Kekule.Editor.Composer(document);
composer.setEnableOperHistory(false);
```

When I draw a molecule with two or more rings (with rings buttons, not drawing them with bonds),
![Molecule with 2 benzene](https://user-images.githubusercontent.com/8458764/64411347-41896400-d08d-11e9-84ff-ce74182a831e.png)

it gives me that strange smiles :
`c1cc(C)ccc1`
(seems that only the first ring drawn is taken in account)

But when I comment out `setEnableOperHistory(false)`, it gives me the correct smiles export:
`c1ccc(cc1)-c2ccccc2`

****
**Some notes :** 
- This behavior is the same when exporting to MOL format.
- When I draw rings manually with bonds, it works, even with operation history disabled.
- I get MOL or SMILES content with these methods:
```javascript
Kekule.IO.saveFormatData(molecule, 'mol');
Kekule.IO.saveFormatData(molecule, 'smi');
```
****

Thank you in advance for your help!

Antonin

**Comment by partridgejiang** [comment]
Thanks a lot for the feedback, and sorry for he delay of replying. Anyway, the bug has been fixed now, please check the latest dist files, :).

**Comment by antonintlh** [comment]
Thank you for your help!
