### ISSUE TITLE
CDN link ?

### ISSUE THREAD

**Issue by ddoyen** [partridgejiang/Kekule.js#137]
Is there a CDN link to include Kekule in a web page ? I can't find it.

**Comment by partridgejiang** [comment]
Hi @ddoyen, since Kekule.js is published on npm, some CDNs have already included it by default. For example, you can use the _unpkg_ service in your HTML code:
```html
<script src="https://unpkg.com/kekule/dist/kekule.js?modules=chemWidget,algorithm"></script>
<link rel="stylesheet" type="text/css" href="https://unpkg.com/kekule/dist/themes/default/kekule.css" />
```

**Comment by ddoyen** [comment]
Thanks !
