### ISSUE TITLE
Documentation gone

### ISSUE THREAD

**Issue by dfd0226** [partridgejiang/Kekule.js#15]
I just yesterday started using your library and it appears the documentation has been overwritten. Just wanted to bring it to your attention if this was unintentional!
![Lorem Ipsum placeholder](https://cloud.githubusercontent.com/assets/2983762/21271636/5c73a544-c381-11e6-83c1-c8b24987a9d6.png)

**Comment by partridgejiang** [comment]
Thanks for your notification and sorry for the delaying of handling it. For some unknown reason the website has been rolled back to a very ancient commit several days before. Now it has been recovered.
