### ISSUE TITLE
Update the download link in gh-pages

### ISSUE THREAD

**Issue by hsiaoyi0504** [partridgejiang/Kekule.js#17]
The download link in the github page is still a release 5 months ago, and it can't be utilized correctly (compressed script). Another suggestion is to create link to the most recent release (I mean the zip file in the repo). Don't use different file names. You can just hyperlink the download link to the most recent release on master branch.

**Comment by partridgejiang** [comment]
Thanks a lot for the reminder, I'll fix it in the next release soon.

**Comment by partridgejiang** [comment]
The link is now updated to current release.
