### ISSUE TITLE
Molecule Mismatch When Element at Different X,Y

### ISSUE THREAD

**Issue by rfedor-macmillan** [partridgejiang/Kekule.js#178]
Hello, I'm new to working with Kekule.js and work with Aaron Llanos and Nate Hayden.  I found an issue with the Kekule library where it is not be matching molecules when an element X, Y coordinate is changed by a few pixels as shown in the screenshot below,
![image](https://user-images.githubusercontent.com/63059525/80036177-dc1ca300-84b6-11ea-9a22-321a45c17a56.png)

Here's the payloads that were used for the comparisons,

Molecule 1 - 
[unshifted-response.json.txt](https://github.com/partridgejiang/Kekule.js/files/4519128/unshifted-response.json.txt)

Molecule 2 - 
[shifted-response.json.txt](https://github.com/partridgejiang/Kekule.js/files/4519129/shifted-response.json.txt)

Thank you for your time.

**Comment by partridgejiang** [comment]
Hi @rfedor-macmillan, in molecule 1, the bonds connected to the bottom chiral center are very near to decussation, so the structure around the chiral center are regarded as a Fischer projection with a certain configuration. While in molecule 2, the structure around the corresponding chiral center is regarded as a normal skeleton with configuration unknown. So the result comparison is false.
If such a behavior is not wanted, you can turn off the Fischer projection detection globally:
```js
Kekule.globalOptions.algorithm.stereoPerception.implicitFischerProjection = false;
```

**Comment by rfedor-macmillan** [comment]
Thank you very much.  I'll be sure to pass that along.
