### ISSUE TITLE
Wedge/Dash bonds - ambiguous stereochemistry cases

### ISSUE THREAD

**Issue by ariccillospark** [partridgejiang/Kekule.js#179]
Hey buddy! I have come across other cases of false positives with wedge/dash bonds. These cases should not match:
![image](https://user-images.githubusercontent.com/29066900/80142967-71d13480-8582-11ea-8271-a40ed0ec055b.png)
![image](https://user-images.githubusercontent.com/29066900/80143130-b6f56680-8582-11ea-8fa3-629d240fc435.png)
![image](https://user-images.githubusercontent.com/29066900/80143197-d68c8f00-8582-11ea-8247-7bb8881a2815.png)
Any ideas or advice will be welcome. Tried to see what was happening and it seems that if the parity is the same, it is matching, but I do not know is the issue is with the parity calculation of the chiral nodes or we need to add other check. Thanks in advance!!

**Comment by partridgejiang** [comment]
Hi @ariccillospark, thanks a lot for the feedback! The issue has been fixed now, please check the latest dist files.
btw, the stereo of reversed wedge bond A►B is considered as B behind A, so it is equal to A<<B（here << indicates the hollow wedge bond）, thus the cases in figure 3 are considered as  two equal structure.

**Comment by ariccillospark** [comment]
@partridgejiang Thank you so much for the fix and the clarification on figure 3!!
