### ISSUE TITLE
Spacing between curved arrow anchors and targets

### ISSUE THREAD

**Issue by mmartinez-macmillan** [partridgejiang/Kekule.js#182]
Is there a way to control the spacing between the curved arrows and their connected targets?

![image](https://user-images.githubusercontent.com/63059258/83194034-97aba500-a0fd-11ea-9df9-df8240af853a.png)

**Comment by partridgejiang** [comment]
Yes, it can be customized globally by the following code:
```js
composer.getRenderConfigs().getLengthConfigs().setGlyphStickOffsetRelLength(0.5);  // set the space to half of default bond length
```
or individually by setting the render option of the curved arrow connector:
```js
arrow.getConnectorAt(0).setRenderOption('glyphStickOffsetRelLength', 0.5);
```

**Comment by mmartinez-macmillan** [comment]
Thank you!
