### ISSUE TITLE
Fail to generate valid SMILES 

### ISSUE THREAD

**Issue by rustamzh** [partridgejiang/Kekule.js#187]
![image](https://user-images.githubusercontent.com/8539796/87858697-38258500-c949-11ea-9b8f-620a0105de29.png)
The SMILES string generated by the molecule on the picture is C/C=C//C=C/C. However, both rdkit and https://metamolecular.com/smidge/ recognize it as an invalid SMILES string (probably due to double forward slash). Can we do something with it? 

P.S Interesting observation: if we remove one bond from molecule the generated SMILES is valid:
![image](https://user-images.githubusercontent.com/8539796/87858768-c7cb3380-c949-11ea-91bf-1d204d9e605f.png)

**Comment by partridgejiang** [comment]
@rustamzh, thanks a lot for the feedback. An fix has been made, please check the latest commit and dist files, :).

**Comment by rustamzh** [comment]
Thank you for the prompt fix!
