### ISSUE TITLE
Add kekule to npm

### ISSUE THREAD

**Issue by Fohlen** [partridgejiang/Kekule.js#20]
I think that it'll probably be really useful to people to have kekule on [npm](https://www.npmjs.com/) to integrate it into their existing workflow (like the majority of JS code nowadays can be found there).

**Comment by Fohlen** [comment]
This will also involve moving the `package.json` to the top of the directory..

**Comment by partridgejiang** [comment]
Thanks for the suggestion. We will investigate it soon, :).

**Comment by ragnerrok** [comment]
There is a PR out to get kekule ready for npm. Please take a look! Would be awesome to have this! ^_^

**Comment by partridgejiang** [comment]
The package has now been published on npmjs.com at https://www.npmjs.com/package/kekule . Thanks for the efforts of @AaronLlanos and @Fohlen.
