### ISSUE TITLE
Select Atom Panel dropdown is empty

### ISSUE THREAD

**Issue by Whitie** [partridgejiang/Kekule.js#203]
When inserting an Atom the Select field shows up. Clicking on the little arrow leads to an empty dropdown. Is there any option I am not seeing to enable the dropdown content?
![kekule_select_panel](https://user-images.githubusercontent.com/6292770/105012705-b79e2900-5a3e-11eb-9950-1e9c741f5b81.png)

**Comment by partridgejiang** [comment]
Hi @Whitie, is there any errors reported in the console of browser? And could you please provide the key part of your HTML/JavaScript codes here? Thanks a lot.

**Comment by Whitie** [comment]
Hi @partridgejiang, thank you for your answer. I think, you can close this here. I have cloned my repo on another PC and there all is fine. Maybe my browser has some caches, which are not OK. On the console was nothing logged.
