### ISSUE TITLE
Atom labels issue.

### ISSUE THREAD

**Issue by cleblond** [partridgejiang/Kekule.js#214]
I recently updated to new version of kekule.js and I noticed the atom label position is off.  Here is a few screenshots
![Screenshot from 2021-02-24 09-57-07](https://user-images.githubusercontent.com/4019904/109019560-1b8fbf00-7687-11eb-834c-9e452f0f5a43.png)

![Screenshot from 2021-02-24 10-01-21](https://user-images.githubusercontent.com/4019904/109019742-467a1300-7687-11eb-85b8-c20a826aa141.png)

**Comment by partridgejiang** [comment]
Hi @cleblond, thanks for the feedback. It looks quite odd, and I can not reproduce it at my own environment. Could more details be provided here? (e.g. the Kekule.VERSION value, the browser, the rendering configuration different from the default value). If possible, could a small demo page be uploaded here? Thanks a lot.

**Comment by cleblond** [comment]
It seems that my framework is setting the global font size and family, so not an issue with kekule.  Thanks.
