### ISSUE TITLE
loading SMILES

### ISSUE THREAD

**Issue by sowiso** [partridgejiang/Kekule.js#215]
I'm trying to load a simple molecule in the composer from a SMILES string, but do not really seem to get the desired result. Here's wat I tried:

```
Kekule.OpenBabel.enable();
let smiles = "C1CCCCC1";
let mol = Kekule.IO.loadFormatData(smiles, "smi");
composer.setChemObj(mol);

```
This does import, but it does not draw very well. The drawing is so tiny, it's only visible when I select it:
![image](https://user-images.githubusercontent.com/1487955/110121446-af1b6b00-7dbe-11eb-8480-57bccab9027c.png)

So I read I could try to generate a 2D sctructure and tried this:

```
Kekule.OpenBabel.enable();
let smiles = "C1CCCCC1";
let mol = Kekule.IO.loadFormatData(smiles, "smi");
let generator = new Kekule.Calculator.ObStructure2DGenerator();
generator.setSourceMol(mol);
generator.executeSync(function() {
    let newMol = generator.getGeneratedMol();
    composer.setChemObj(newMol);
});
```

This works better, but now it looks like this:
![image](https://user-images.githubusercontent.com/1487955/110121681-face1480-7dbe-11eb-852f-984fd4cd1c73.png)
And the console shows this 
![image](https://user-images.githubusercontent.com/1487955/110121862-3537b180-7dbf-11eb-81cc-b2a0ca87f817.png)

Is there a way to get the smiles = "C1CCCCC1" look like this?

![image](https://user-images.githubusercontent.com/1487955/110121955-500a2600-7dbf-11eb-853d-bdc2631fc57c.png)

Thanks

**Comment by partridgejiang** [comment]
@sowiso, thanks for the feedback, we have found  a bug in ObStructureGenerator.executeSync causing it always returns the 3D structure generated.
Currently, as a workaround, please use the ```execute``` method rather than ```executeSync```:
```js
Kekule.OpenBabel.enable(() => {
  let smiles = "C1CCCCC1";
  let mol = Kekule.IO.loadFormatData(smiles, "smi");
  let generator = new Kekule.Calculator.ObStructure2DGenerator();
  generator.setSourceMol(mol);
  generator.execute(err => {    // using execute rather than executeSync
    if (!err)
    {
      let newMol = generator.getGeneratedMol();
      composer.setChemObj(newMol);
    }
  });
});
```
The ``` execute``` method runs in web worker, so it may even provide a better user experience.
By the way, in recent versions, you can also utilize the newly introduced ```setChemObjData``` method:
```js
Kekule.OpenBabel.enable(() => {
  composer.getEditor().setChemObjData('{"format": "smi", "data": "C1CCCCC1"}')
});
```
In default settings, when the editor detects that the input molecule is a 0D one(with out coordinates), it will automatically generate them for the molecule.

**Comment by sowiso** [comment]
Thanks a lot @partridgejiang 
I got it to work correctly now with `execute()`. However, when I call it a second time, it seems like it's not working anymore, whereas `executeSync()` is.

**Comment by sowiso** [comment]
It looks like I get a similar behaviour when I load smiles manually via the menu. These steps reproduce the issue:

1. click "load data", format SMILES, input C1CC1 and click OK
2. the molecule is now drawn
2. click "Create new document"
3. repeat step 1 (click "load data", format SMILES, input C1CC1 and click OK)
4. the molecule is now not drawn anymore

**Comment by partridgejiang** [comment]
Hi @sowiso, the bugs in both execute() and executeSync() should be fixed now, please check the latest dist files, :).

**Comment by sowiso** [comment]
Confirmed, this works perfectly now. Thanks!
