### ISSUE TITLE
Chinese and English confusion in the toolbar

### ISSUE THREAD

**Issue by niuzhenjiang** [partridgejiang/Kekule.js#231]
Chinese and English confusion in the toolbar，
i use newest version:
<script src="static/js/kekule/kekule.min.js"></script>
please fix the problem，thank you very much!!
<img width="634" alt="截屏2021-06-26 下午2 38 51" src="https://user-images.githubusercontent.com/42111602/123504525-7284bf80-d68c-11eb-8ec3-3ab39622d2db.png">
<img width="638" alt="截屏2021-06-26 下午2 36 32" src="https://user-images.githubusercontent.com/42111602/123504528-73b5ec80-d68c-11eb-8cf9-c6ac6052bba8.png">

**Comment by partridgejiang** [comment]
Hi @niuzhenjiang, it seems the language resources is not fully loaded in your page. Could you check the ```Kekule.VERSION``` value , or try with the latest dist file in this repository? The latest version should be 0.9.7.

**Comment by niuzhenjiang** [comment]
<img width="1440" alt="截屏2021-06-27 下午1 26 39" src="https://user-images.githubusercontent.com/42111602/123533846-6449a880-d74b-11eb-9464-dca5e65ee306.png">
my kekule version is 0.9.7，i'm download this latest resources from your master, it have this languange problem，but i use it :
<script src="static/js/kekule/kekule.min.js"></script>
Do I need to use other function to load language files?

**Comment by partridgejiang** [comment]
Hi @niuzhenjiang, thanks for the feedback. The issue is caused by a wrong minimization sequence of kekule.min.js and has now been fixed. Please check the latest dist files.

**Comment by niuzhenjiang** [comment]
it works，thank you very much~，but i want to ask a question:
when i load kekule.min.js, it default set chinese,i want to set english,how can i do it?

**Comment by partridgejiang** [comment]
By default, Kekule.js will detect the language settings of the web browser and use the corresponding language resources (Chinese or English) automatically. The language can also be appointed manually. When using kekule.js (not kekule.min.js), extra language params in <script> tag can be used:
```js
<script src="lib/kekule.js?locals=en,zh&language=en"></script>
```
A new update has been made in today's commits to enable set language by a special global variable when using kekule.min.js:
```js
<script>
  _kekule_environment_ = { 'kekule.language': 'en' }
</script>
<script src="lib/kekule.min.js"></script>
```
Please check the latest dist files.

**Comment by niuzhenjiang** [comment]
wow, it's nice,thank you very much~

**Comment by TangTangJia** [comment]
> By default, Kekule.js will detect the language settings of the web browser and use the corresponding language resources (Chinese or English) automatically. The language can also be appointed manually. When using kekule.js (not kekule.min.js), extra language params in <script> tag can be used:
> 
> ```js
> <script src="lib/kekule.js?locals=en,zh&language=en"></script>
> ```
> 
> A new update has been made in today's commits to enable set language by a special global variable when using kekule.min.js:
> 
> ```js
> <script>
>   _kekule_environment_ = { 'kekule.language': 'en' }
> </script>
> <script src="lib/kekule.min.js"></script>
> ```
> 
> Please check the latest dist files.


Can I set the language programmatically?
