### ISSUE TITLE
export smiles

### ISSUE THREAD

**Issue by TangTangJia** [partridgejiang/Kekule.js#235]
Thanks for your contribution ！

I want to export smiles , but it's always export empty. I try to export 'cml' and it works.

```
const Kekule = require('kekule')
const mol = new Kekule.Molecule()
const smiles = Kekule.IO.saveFormatData(mol, 'smi')
console.log('SMILES: ', smiles)
```

**Comment by niuzhenjiang** [comment]
let molecule = composer.getChemObj();
smiles_data = Kekule.IO.saveFormatData(molecule, 'smi');
console.log(smiles_data)

**Comment by TangTangJia** [comment]
> let molecule = composer.getChemObj();
> smiles_data = Kekule.IO.saveFormatData(molecule, 'smi');
> console.log(smiles_data)

thanks for your answer, it works!
