### ISSUE TITLE
set language

### ISSUE THREAD

**Issue by TangTangJia** [partridgejiang/Kekule.js#237]
in my project，the default language is English，how can I set chinese programmatically?

![1625213801(1)](https://user-images.githubusercontent.com/34622385/124244011-140a8600-db51-11eb-9985-2d47dd23f62e.png)

**Comment by partridgejiang** [comment]
Hi @TangTangJia, at present, the localization resources of existing widgets can not be reloaded automatically. So it is not recommended to change the language after initialization. You have to appoint the language before loading Kekule.js files, either by special params in <script> tag:
```html
<script src="lib/kekule.js?locals=en,zh&language=zh"></script>  <!-- or <script src="lib/kekule.min.js?locals=en,zh&language=zh"> in latest dist -->
```
or by a special global variable:
```html
<script>
  _kekule_environment_ = { 'kekule.language': 'en' }
</script>
<script src="lib/kekule.min.js"></script>
```

**Comment by TangTangJia** [comment]
@partridgejiang     thanks for your reply，however i installed it by npm, i don't know how to appoint the language before loading Kekule.js files

**Comment by partridgejiang** [comment]
The latter approach should also be usable here, just put the _kekule_environment_ setting codes before the bundled js in your HTML:
```html
<script>
  _kekule_environment_ = { 'kekule.language': 'en' }
</script>
<script src="bundle.js"></script>
```
By the way, the latest dist from this repository is needed to replace the Kekule.js lib directly installed from npm.
