### ISSUE TITLE
download file function

### ISSUE THREAD

**Issue by niuzhenjiang** [partridgejiang/Kekule.js#238]
i want to add custom button: it can download *.smi,*.sdf,*.mol format file.
i believe kekule have this functions. but i can't search this functions from doc.
how can i do it can bind these download event.

**Comment by partridgejiang** [comment]
Hi @niuzhenjiang, this function is encapsulated in ```Kekule.NativeServices.saveFileData``` method (you can check it in html/kekule.nativeServices.js, line 174). The download code may be something like the following:
```js
btn.onclick = function(e){
   Kekule.NativeServices.saveFileData(document, data, null, {'initialFileName': 'myData.smi'});
}
```

**Comment by niuzhenjiang** [comment]
thank you so much ,it worked~
