### ISSUE TITLE
viewing JCAMP-DX?

### ISSUE THREAD

**Issue by registerme1963** [partridgejiang/Kekule.js#242]
Hi,
Is there any option to include viewing NMR, IR, Mass data using JCAMP-DX format? If not are there any plans for that in future?
thanks

**Comment by partridgejiang** [comment]
Currently JCAMP-DX format is not supported yet but there do exists plans for it, :).

**Comment by registerme1963** [comment]
is there any timeline? We are planning for integration with Gaussian/NWChem and others for full blown web based chemistry app?
Thanks

**Comment by partridgejiang** [comment]
There is no precise timeline yet, perhaps in several months.

**Comment by registerme1963** [comment]
After deleting the last 0, it is now loading. Sorry to quote another competing product, is it possible to have zoom like
[https://web.chemdoodle.com/tutorial/spectrum-canvases/perspective-canvas](https://web.chemdoodle.com/tutorial/spectrum-canvases/perspective-canvas)
and structure correlation like
[https://web.chemdoodle.com/tutorial/advanced/structurespectrum-correlations](https://web.chemdoodle.com/tutorial/advanced/structurespectrum-correlations)
and also some documentation how to go about it
it would be great for my organic spectroscopy teaching

**Comment by registerme1963** [comment]
How do I implement this in moodle page?

**Comment by partridgejiang** [comment]
The Kekule-Moodle plugins are not updated with those spectrum functions yet, please wait for a while.
By the way, the Viewer widget has been expanded to support interactions of spectrum (including zoom, moving, hot tracking, peak selecting, etc.) now. You may check the ```test/widgetTest/chemWidgets/spectrumViewerTest.html``` page in ```Spectra``` branch of this repository for a preview of it, :).

**Comment by partridgejiang** [comment]
A new widget (ChemWidget.SpectrumInspector) is now introduced to display the spectrum-molecule correlation as a supplement of ChemWidget.Viewer. Demo (http://partridgejiang.github.io/Kekule.js/demos/items/spectrum/spectrumInspector.html) and tutorial documents (http://partridgejiang.github.io/Kekule.js/documents/tutorial/content/spectra.html) have been published on the website as well. 
The Kekule-Moodle plugin has also been expanded with a new atto button to insert spectrum with HTML editors in Moodle.

**Comment by partridgejiang** [comment]
A new widget (ChemWidget.SpectrumInspector) is now introduced to display the spectrum-molecule correlation as a supplement of ChemWidget.Viewer. Demo (http://partridgejiang.github.io/Kekule.js/demos/items/spectrum/spectrumInspector.html) and tutorial documents (http://partridgejiang.github.io/Kekule.js/documents/tutorial/content/spectra.html) have been published on the website as well. 
The Kekule-Moodle plugin has also been expanded with a new atto button to insert spectrum with HTML editors in Moodle.

**Comment by registerme1963** [comment]
Thank you very much. 
Let me try it out and get back to you.
