### ISSUE TITLE
Set wedge and dash bond size on autoFit

### ISSUE THREAD

**Issue by akulmehta** [partridgejiang/Kekule.js#247]
I have set autoFit on the chem viewer 2D which scales as described in the following issue 33: https://github.com/partridgejiang/Kekule.js/issues/33#issuecomment-593766313

The main issue now is that the wedge and dash bond sizes are too big or invisible respectively. See structure as example:
![image](https://user-images.githubusercontent.com/42812604/128192364-e23d29d4-1a1c-44c9-9ea3-8756c6b99907.png)

Anyways I can adjust the sizes for the wedges and dashed when it does do the autofit?

Alternatively is it possible to ignore wedge/dash when autofit is performed?

Thank you so much for creating this wonderful package.

**Comment by partridgejiang** [comment]
Hi @akulmehta, you can always adjust the width of wedge bonds with the following codes:
```js
chemViewer.getRenderConfigs().getLengthConfigs().setBondWedgeWidth(3);  // use custom width of wedge end
```

**Comment by akulmehta** [comment]
@partridgejiang but what about the dash bonds?

**Comment by partridgejiang** [comment]
The hash bond width shares the same setting to wedge bond. By the way, spacing between dashes is also settable:
```js
chemViewer.getRenderConfigs().getLengthConfigs().setHashSpacing(2);
```
