### ISSUE TITLE
export cropped image

### ISSUE THREAD

**Issue by lsdsjy** [partridgejiang/Kekule.js#252]
In chemComposer, how can I export the current chem obj into an image cropped to its surrounding box?
I tried `exportToDataUri` but it seems to export the whole canvas, which has plenty of blanks.

**Comment by partridgejiang** [comment]
A simple approach is to create a autosized viewer widget, load the objects inside composer to the viewer, then export image from the viewer:
```js
// create a hidden autosized viewer widget
let viewer = new Kekule.ChemWidget.Viewer(document);
viewer.appendToElem(document.body);
viewer.getElement().style.visibility = 'hidden';
viewer.setAutoSize(true);
// load objects in viewer
viewer.setChemObj(composer.getChemObj());
// export image
let dataUri = viewer.exportToDataUri();
```

**Comment by lsdsjy** [comment]
@partridgejiang Thanks!
