### ISSUE TITLE
Request for aromatic benzene ring

### ISSUE THREAD

**Issue by kuaaangwen** [partridgejiang/Kekule.js#264]
Hi partridgejiang,

Thank you so much for this! It's amazing work!

Would it be possible for you to include the aromatic structure of benzene in the chem widget? I am able to draw the kekule structure, but I cannot draw one with a ring in it.

Thank you!

**Comment by partridgejiang** [comment]
Hi @kuaaangwen, this feature may be added in the future, but it did require some time. Drawing a hexagon and a circle for benzene is simple, but in some situations, the behavior may be quite complex when the benzene ring being modified in the editor (e.g., adding another benzene ring side by side to create naphthalin, changing one carbon atom to nitrogen to create pyridine, deleting one bond on the ring, etc). 
Currently, as a alternate, you may create a Kekule structure in the composer widget first, then select the whole ring, click on the "Set bond" button at the bottom of composer and in the drop down panel, select the "Hucklize" tool. Afterward, six explicit "aromatic bond" will be displayed inside the ring.

**Comment by kuaaangwen** [comment]
@partridgejiang thank you so much for the response! I look forward to the day the function is built! Let me know if I can help in any way. And thanks for the suggestion!
