### ISSUE TITLE
Allow symbols for atom without throwing error

### ISSUE THREAD

**Issue by agrodet** [partridgejiang/Kekule.js#278]
Hello. In https://github.com/partridgejiang/Kekule.js/issues/135 , you mentioned a way to forbid unknown atom symbols. Is there any way to allow some additional symbols? In particular, I would like to be able to use `*` without throwing any error, especially the following bar
![image](https://user-images.githubusercontent.com/42261966/163900949-713799ba-286f-4598-9cc9-e770c21844a9.png)

Even with `setAllowUnknownAtomSymbol(true)`, I'm facing an error if I modify, let's say an oxygen atom to *, but the label is replaced. However, if I try to do it a second time, I'm facing an error that doesn't let me do anything. 

Notice that the SMILES is generated with `*` as expected `COc1cc(ccc1)CNC(=O)c2cc3c(cc2)n(c(n3)N)CCC[*]C`.

**Comment by agrodet** [comment]
Dear @partridgejiang, thank you for your prompt response! I understand the problem. I'm facing the issue I mentioned when using the "Set atom" button of the "Select tool". I've made a small video.

https://user-images.githubusercontent.com/42261966/165202219-2c826b2f-ee11-49bf-bf61-ed5cc8dbe26e.mov

**Comment by partridgejiang** [comment]
Thanks for the attached video helping to locate the bug. Now a fix has been made, please check the new dist file and have a test.

**Comment by agrodet** [comment]
Thank you. It seems that everything is working as expected now.
