### ISSUE TITLE
Is it possible to choose the starting atom when converting to smiles

### ISSUE THREAD

**Issue by agrodet** [partridgejiang/Kekule.js#279]
Maybe it is not a question directly related to Kekule, but I was wondering if there was a way to choose an atom to be the first of the SMILES string when using `saveFormatData()` (or any other way, if there is).

**Comment by partridgejiang** [comment]
Unfortunately such a task is not available when saving SMILES currently. A molecule canonicalization will always be processed before outputting SMILES in Kekule.js. However, when saving to MOL or JSON format data, such a canonicalization can be bypassed and the atom sequence may be customized, e.g.:

```js
let atoms = molecule.getNodes();
// change atom orders here, atoms is a simple array and can be sorted
atoms.sort(myCustomSortMethod);
// and then output directly
let molData = Kekule.IO.saveFormatData(molecule, Kekule.IO.DataFormat.MOL);
```

**Comment by agrodet** [comment]
Thank you for your explanation.
