### ISSUE TITLE
Struggling to use Kekule with next.js

### ISSUE THREAD

**Issue by Benjaki2** [partridgejiang/Kekule.js#280]
[Next.js docs](https://nextjs.org/docs/api-reference/edge-runtime#unsupported-apis) say `Calling require directly is not allowed. Use ES Modules instead`. It appears the middleware does not allow for this.

Error I see:
```
./node_modules/kekule/dist/kekule.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```
For what it's worth, Kekule seems to work when not present on initial load.

I am considering trying to transpile the code to ES6 modules with something like the `cjs-to-es6` npm module. @partridgejiang do you have any suggestions?
Thank you for all your work/help!

**Comment by filoscoder** [comment]
@Benjaki2 did you find a solution?

**Comment by Benjaki2** [comment]
Thanks @partridgejiang.

@filoscoder My solution was a mix of what @partridgejiang stated above and [dynamic imports](https://nextjs.org/docs/advanced-features/dynamic-import). The solution does not do SSR (server-side-rendering) but it works.

**Comment by Benjaki2** [comment]
relates to #262  --- closing.
