### ISSUE TITLE
making the molecules to be in focus

### ISSUE THREAD

**Issue by joeolu14** [partridgejiang/Kekule.js#305]
When I load the molecule to the editor, I load in mol format. This is what my editor looks like 
![image](https://user-images.githubusercontent.com/94984457/233813513-4904eb18-9828-473c-9958-2e4a81dc27c6.png)

I will have to scroll to where the molecules are, is there a way to scroll or autofocus on the molecule loaded like this 
![image](https://user-images.githubusercontent.com/94984457/233813543-baff7027-7c0f-404f-be6d-dac713bfc53e.png)

Also is there a way to reduce the zoom as the zoom is way bigger than expected. 

This is my setup 
```js
const MolEditor: FC<MolEditorProps> = ({ molecule, id, width, height }) => {
  useEffect(() => {
    if (molecule && id) {
      setTimeout(() => {
        const composer = Kekule.Widget.getWidgetById(id);
        composer.setCommonToolButtons([
          // "newDoc",
          "copy",
          "undo",
          "redo",
          "cut",
          "paste",
          "zoomIn",
          "zoomOut",
          "objInspector",
        ]);
        const myMolecule = new Kekule.IO.loadFormatData(molecule, "mol");

        composer.setChemObj(myMolecule);
      }, 200);
    }
  }, [molecule, id]);

  return (
    <Container key={id}>
      <div
        id={id}
        style={{
          width,
          height,
          textAlign: "center",
        }}
        data-widget="Kekule.Editor.Composer"
      ></div>
    </Container>
  );
};
```

**Comment by partridgejiang** [comment]
Hi @joeolu14, the method ```scrollClientToObject``` can be used to scroll to object inside editor:
```js
// ...
composer.setChemObj(myMolecule);
composer.getEditor().scrollClientToObject(myMolecule);
```

The ```zoomTo``` method can be used to change the current zoom level of editor:
```js
composer.zoomTo(0.75);
```
And the ```initialZoom``` controls the initial zoom level when loading or creating new object in editor:
```js
composer.setInitialZoom(1);  // The default initial zoom level is 1.5 for some historical reason
```

**Comment by joeolu14** [comment]
> Hi @joeolu14, the method `scrollClientToObject` can be used to scroll to object inside editor:
> 
> ```js
> // ...
> composer.setChemObj(myMolecule);
> composer.getEditor().scrollClientToObject(myMolecule);
> ```
> 
> The `zoomTo` method can be used to change the current zoom level of editor:
> 
> ```js
> composer.zoomTo(0.75);
> ```
> 
> And the `initialZoom` controls the initial zoom level when loading or creating new object in editor:
> 
> ```js
> composer.setInitialZoom(1);  // The default initial zoom level is 1.5 for some historical reason
> ```

Just tried and the scrollClientToObject seem to work but scrolls to the starting point of the molecule, I am trying to get the molecule  in the middle of the canvas. 
![image](https://user-images.githubusercontent.com/94984457/234000312-e985bc8e-1345-437b-94bc-6a79ab9067ba.png)

Also the setInitialZoom and zoomTo functions do now exist, it throws an error when I try to use them.

**Comment by partridgejiang** [comment]
Sorry I have made a mistake about the zoom related properties and methods, these properties/methods are located in editor object rather than the composer, so the code should be:
```js
composer.getEditor().zoomTo(0.75);
composer.getEditor().setInitialZoom(1);
```
And for the scrolling, you may also try the extra option param of ```scrollClientToObject```:
```js
composer.getEditor().scrollClientToObject(myMolecule, {scrollToCenter: true, coverMostObjs: true});
```

**Comment by joeolu14** [comment]
Thanks @partridgejiang, I will like to know how to save the molecule as svg? is there a function for this?

**Comment by partridgejiang** [comment]
Hi @joeolu14, there is an online demo for exporting to SVG ( http://partridgejiang.github.io/Kekule.js/demos/items/chemEditor/exportSVG.html ). In brief, a special hidden viewer with SVG renderer need to be created and used to output the SVG code for chem objects.

**Comment by joeolu14** [comment]
@partridgejiang yes I saw the implementation but I could not reproduce same for a simple react application

**Comment by joeolu14** [comment]
@partridgejiang In the root of my component I made this declaration 
```js
  Kekule.ChemWidget.Viewer2DSvg = Object.assign(Kekule.ChemWidget.Viewer2D, {
    CLASS_NAME: "Kekule.ChemWidget.Viewer2DSvg",
    // @ts-ignore
    createDrawBridge: function ($super, slient) {
      if (Kekule.Render.RaphaelRendererBridge) { 
        return new Kekule.Render.RaphaelRendererBridge();
      } else { 
        return $super(slient);
      }
    },
  });
```
And this is function to generate the SVG image
```js
  const generateImage = () => {
    const composer = Kekule.Widget.getWidgetById("composer");  
    
    const chemViewer = Kekule.Widget.getWidgetById("chemViewer");
    var chemObj = composer.getSavingTargetObj();

    if (chemObj) { 
      chemViewer.setChemObj(chemObj); 
      var context = chemViewer.getDrawContext();  
      if (context && context.toSVG) {
        var svg = context.toSVG();
        console.log("SVG: ", svg);
        alert(svg);
      }
    }  
  };
```
But context does not seem to have the .toSVG function 
This is where I load the viewer to the page
```js
   <div style={{ marginTop: "50px", textAlign: "center" }}>
        <div
          id="chemViewer"
          style={{
            width: "800px",
            height: "400px",
          }}
          data-widget="Kekule.ChemWidget.Viewer2DSvg" 
        ></div>
      </div>
```
