### ISSUE TITLE
Save molecules in Inchi format

### ISSUE THREAD

**Issue by joeolu14** [partridgejiang/Kekule.js#306]
Is there a way to saveFormatData in Inchi format? 

This what I tried but did not work 

```js
 const generateMoleCules = async () => {
    const composer = Kekule.Widget.getWidgetById("composer");
    const mols = composer.exportObjs(Kekule.Molecule);
    const msg = "Molecule count: " + mols.length + "\n ";
    const m = [];
    for (let i = 0, l = mols.length; i < l; ++i) {
      const mol = mols[i];
      m.push(Kekule.IO.saveFormatData(mol, "smi"));
      const abc = Kekule.IO.saveFormatData(mol, "mol");

      const ccc = Kekule.InChI.molDataToInChI(mol);

      console.log(ccc);

      setMole(m); 
    }
  };

```

**Comment by partridgejiang** [comment]
Hi @joeolu14, since InChI is actually a external wasm module, you need to manuallt enable the InChI functions before using them, e.g.:
```js
Kekule.InChI.enable( error => {
  if (!error) {
    let inchi = Kekule.IO.saveFormatData(mol, 'inchi');
    console.log(inchi);
  }
});
```

**Comment by joeolu14** [comment]
@partridgejiang I tried the above and got this error:
![image](https://user-images.githubusercontent.com/94984457/236216362-84720fc5-9dac-452e-9949-8773784bd26b.png)

This is what the code looks like:
```js
  const generateMoleCules = async () => {
    const composer = Kekule.Widget.getWidgetById("composer");
    const mols = composer.exportObjs(Kekule.Molecule);
    const msg = "Molecule count: " + mols.length + "\n ";
    const m = [];
    for (let i = 0, l = mols.length; i < l; ++i) {
      const mol = mols[i];
      m.push(Kekule.IO.saveFormatData(mol, "smi"));
      Kekule.InChI.enable((error: any) => {
        if (!error) {
          let inchi = Kekule.IO.saveFormatData(mol, "inchi");
          console.log(inchi);
        }
      });
      setMole(m);
    }
  };
```

**Comment by partridgejiang** [comment]
Hi @joeolu14, The error displayed ( ```Unexpected token '<'``` ) seems caused by the web server? Is content of inchi.wasm properly returned by server? Perhaps you could switch to the network panel of developer tools in web browser to check which files and contents are transfered when ```Kekule.InChI.enable()``` being called.

**Comment by joeolu14** [comment]
@partridgejiang I saw the error, I had to copy the libs to my static folder to avoid the error, but the issue now is, the inchi is not being created and does not look like anything inside the enable block gets read. This is what my code looks like
```js
  const generateMoleCules = async () => {
    const composer = Kekule.Widget.getWidgetById("composer");
    const mols = composer.exportObjs(Kekule.Molecule);
    const msg = "Molecule count: " + mols.length + "\n ";
    const m = [];
    for (let i = 0, l = mols.length; i < l; ++i) {
      const mol = mols[i];

      m.push(Kekule.IO.saveFormatData(mol, "mol"));

      Kekule.InChI.enable((error: any) => {
        if (error) {
          console.log(error);
        }
        if (!error) {
          let inchi = Kekule.IO.saveFormatData(mol, "inchi");
          console.log(inchi, "inchi");
        }
      });

      setMole(m);
    }
  };
```

is there anything to do to get this working?

**Comment by partridgejiang** [comment]
Hi @joeolu14, you may check the status of Kekule InChI module in the console of the web development tool to find out whether the module is properly loaded and initialized:
```js
Kekule.InChI.isScriptLoaded()    // should returns true if the wasm is loaded
```
```js
Kekule.InChI.getInChIScriptUrl()   // should returns the path to the inchi.js
```

If the ```Kekule.InChI.getInChIScriptUrl()``` is different from the actual location of inchi.js (and inchi.wasm), you need to manually set it before calling ```Kekule.InChI.enable()```:

```js
Kekule.environment.setEnvVar('inchi.scriptSrc', '/the/real/path/to/inchi.js');
// ...
Kekule.InChI.enable(...);
```

**Comment by joeolu14** [comment]
@partridgejiang when I checked isScriptLoaded() it returns false. the getInchiScriptUrl() is pointed to where I have the inchi.js and the wasm

**Comment by partridgejiang** [comment]
@joeolu14, would you please provide a simple demo file of you app here? So that I may debug it in my environment? Thanks.
