### ISSUE TITLE
Viewer enable zoom but disabling pan

### ISSUE THREAD

**Issue by joeolu14** [partridgejiang/Kekule.js#307]
Hi, 

Is there a way to enable zoom but not pan? 

I tried using the `enableDirectInteraction = false,` but that disables both functionalities. I would love to keep the zoom. Is this possible?

**Comment by partridgejiang** [comment]
Hi @joeolu14, please download the newly commited dist files. Some new properties and methods have been added to viewer widget. To disable zoom but not pan, the following code can be used:
```js
viewer.setEnabledOfDirectInteractionMode('move', false)
  .setEnabledOfDirectInteractionMode('zoom', true);
```

**Comment by joeolu14** [comment]
@partridgejiang I sorted this out, did not have to use the new dist. I had to use the onWheelCapture event with the zoomIn() and zoomOut() functions of the viewer.
