### ISSUE TITLE
Extra explicit hydrogen being added to atoms in drawer

### ISSUE THREAD

**Issue by Luckp1089** [partridgejiang/Kekule.js#312]
Hello!

When working in the Chem Composer, instead of seeing a charge, an extra 'H' atom appears on Nitrogen and Chlorine when I add a bond that would usually result in a positive charge for the atom:

<img width="1132" alt="image" src="https://github.com/partridgejiang/Kekule.js/assets/71799235/36a98377-c833-4260-91e7-4b84edc02e7f">

Is there any way to toggle this off so that the extra hydrogen atom does not appear? Or is there a way to have it automatically replaced with a positive charge?

Thanks!!

**Comment by partridgejiang** [comment]
Hi @Luckp1089, you may turn the implicit hydrogen calculation off to do this:
```js
Kekule.globalOptions.structure.implicitHydrogenEstimationStrategy.targetElements['Cl'] = false;
Kekule.globalOptions.structure.implicitHydrogenEstimationStrategy.targetElements['N'] = false;
```
However, the charge still need to be added manually, there is no build-in automatic mechanism for this.

**Comment by Luckp1089** [comment]
Excellent! Thank you for the response! Closing the issue now
