### ISSUE TITLE
How to change default activated buttons in Composer?

### ISSUE THREAD

**Issue by michael-striewe** [partridgejiang/Kekule.js#313]
I'm a happy user of the Composer due to its great capabilities for customization. In my project, I frequently create composer instances with some buttons removed. However, I have not yet found a way to change the default activated buttons.

Example: If I use the ring structures tool, the default activated button in the bottom panel is Cyclopropane. If I remove that button, no other button is activated by default. In fact, Cyclopropane is still activated, so if I click into the drawing canvas without selecting any other button, I still get Cyclopropane.

Is there any way to change this behaviour? In none of my use cases, Cyclopropane is a reasonable default, so I would like to change the default to Cyclohexan or Benzene.

**Comment by partridgejiang** [comment]
Hi @michael-striewe, you may use the following approach (although a little hacky) to change the default activated action of a chem tool after the composer being created:

```js
let actionMap = composer.getActionMap();
// change the default action to cyclopropane
actionMap.get(Kekule.Editor.ActionComposerSetRepositoryRingController)
  .setDefaultAttachedAction(actionMap.get(Kekule.Editor.ActionComposerSetRepositoryRing6Controller));  
// or change the default action to benzene
actionMap.get(Kekule.Editor.ActionComposerSetRepositoryRingController)
  .setDefaultAttachedAction(actionMap.get(Kekule.Editor.ActionComposerSetRepositoryRingAr6Controller));  
```

**Comment by michael-striewe** [comment]
Thank you very much for the quick reply. That works perfectly and solves this issue!
