### ISSUE TITLE
Hello, buddy. I'm trying to use kekule-vue. How can I localize it to Chinese?

### ISSUE THREAD

**Issue by summerooo** [partridgejiang/Kekule.js#322]
你好，老哥，我尝试使用kekule-vue，请问如何汉化呀，

**Comment by partridgejiang** [comment]
不需要做什么特别处理啊，import kekule与kekule-vue后，程序会自动检测浏览器语言。如果发现是中文环境，会自动使用汉语资源的：
```vue
<script setup>
import 'kekule';
import 'kekule/theme';
import { Components } from 'kekule-vue';

const Composer = Components.Composer;
</script>

<template>
  <section>
    <Composer></Composer>
  </section>
</template>
```
请参考附件中的简单示例：
[kekule-vue-vite.zip](https://github.com/user-attachments/files/16824787/kekule-vue-vite.zip)

**Comment by summerooo** [comment]
这样啊，感谢老哥
我换成你这个引入可以了。
之前是clone的你之前的kekule-vue 引入的是
import { Kekule } from 'kekule/mod/chemWidget'
import 'kekule/theme'
可能是这个导致一直是英文

**Comment by summerooo** [comment]
> 不需要做什么特别处理啊，import kekule与kekule-vue后，程序会自动检测浏览器语言。如果发现是中文环境，会自动使用汉语资源的：
> 
> ```
> <script setup>
> import 'kekule';
> import 'kekule/theme';
> import { Components } from 'kekule-vue';
> 
> const Composer = Components.Composer;
> </script>
> 
> <template>
>   <section>
>     <Composer></Composer>
>   </section>
> </template>
> ```
> 
> 请参考附件中的简单示例： [kekule-vue-vite.zip](https://github.com/user-attachments/files/16824787/kekule-vue-vite.zip)

你好老哥，以下是遇到的疑惑。

1. https://partridgejiang.github.io/Kekule.js/demos/items/chemViewer/chemViewer2D.html
导出OpenBabel ，导入SMILES，这个开启更多文件导入导出 vue是对应的api是那个呀

2. 加载的.mol数据如何追加到编辑框中呢,现在是直接覆盖了。

`<template>
	<div class="container">
		<button @click="test">aaa</button>
		<button @click="test1">bbb</button>
		<div class="content">
			<composer class="left" id="composer" ref="composer" vue-predefined-setting="fullFunc" v-model="chemObj"
				v-model:vueSelection="selection" v-model:vueHotTrackedObjs="hotTrackedObjs"
				@userModificationDone="onComposerUserModificationDone" v-model:vueShowObjInspector="showObjInspector"
				v-model:vueShowIssueInspector="showIssueInspector"></composer>
			<viewer class="right" id="viewer" ref="viewer" vue-predefined-setting="fullFunc" :vue-chem-obj="chemObj"
				:vue-render-type="3"></viewer>
		</div>
	</div>
</template>

<script>
import 'kekule'
import 'kekule/theme'
import * as THREE from 'three'
Kekule.externalResourceManager.register('three.js', THREE);
import { Components } from 'kekule-vue'
console.log(Kekule.Render, 'Kekule.Render.rendererType.R3D')

let Viewer = Components.Viewer;
let Composer = Components.Composer;

var N = Kekule.ChemWidget.ComponentWidgetNames;
var C = Kekule.Editor.ObjModifier.Category;
console.log(N, C, 'NC')

export default {
	name: "composerAndViewer",
	components: { Viewer, Composer },
	data() {
		return {
			'chemObj': undefined,
			selection: undefined,
			hotTrackedObjs: undefined,

			showObjInspector: undefined,
			showIssueInspector: undefined
		}
	},
	mounted() {
		console.log(this.$refs.composer.getWidget(), )
	},
	methods: {
		test() {
			this.$refs.composer.getWidget()
				.setEnableOperHistory(true)
				.setEnableLoadNewFile(true)
				.setEnableCreateNewDoc(true)
				.setAllowCreateNewChild(true)
				.setCommonToolButtons(["newDoc",
					"loadData",
					"saveData",
					"undo",
					"redo",
					"copy",
					"cut",
					"paste",
					"zoomIn",
					"zoomOut",
					"config",
					"objInspector", {
						"name": "commonCustom1",
						// use your own Action class here to do some concrete work
						"actionClass": Class.create(Kekule.Editor.ActionOnComposerAdv, {}),
						"hint": "Custom action 1"
					},])   // create all default common tool buttons
				.setChemToolButtons(['manipulate', 'erase', 'bond', 'atom', 'formula',
					'ring', 'charge', 'glyph', 'textAndImage'])   // create all default chem tool buttons
				.setStyleToolComponentNames(['fontName', 'fontSize', 'color',
					'textDirection', 'textAlign']);  // create all default style components
		},
		test1() {
			let that = this
			var resId = 'url(#molResExternalLink)';
			Kekule.IO.loadResourceData('url(#molResExternalLink)', function (mol, success) {
				if (success) {
					that.chemObj = mol
					console.log('Loading from ' + resId + ' Successful');
					console.log(mol, success)
				}
				else {
					console.log('Loading from ' + resId + ' Failed');
				}
			});
		},
		onComposerUserModificationDone() {
			// console.log(this.$refs.composer.getWidget())
			this.$refs.viewer.getWidget().requestRepaint();
		}
	}
}
</script>

<style scoped>
.container {
	width: 100vw;
	height: 100vh;
	display: flex;
	flex-direction: column;
	align-items: flex-start;
}

.container .content {
	width: 100%;
	flex: 1;
	display: flex;
}

.container .left,
.container .right {
	flex: 1;
}
</style>`

**Comment by summerooo** [comment]
> 不需要做什么特别处理啊，import kekule与kekule-vue后，程序会自动检测浏览器语言。如果发现是中文环境，会自动使用汉语资源的：
> 
> ```
> <script setup>
> import 'kekule';
> import 'kekule/theme';
> import { Components } from 'kekule-vue';
> 
> const Composer = Components.Composer;
> </script>
> 
> <template>
>   <section>
>     <Composer></Composer>
>   </section>
> </template>
> ```
> 
> 请参考附件中的简单示例： [kekule-vue-vite.zip](https://github.com/user-attachments/files/16824787/kekule-vue-vite.zip)

你好老哥，以下是遇到的疑惑。

1. https://partridgejiang.github.io/Kekule.js/demos/items/chemViewer/chemViewer2D.html
导出OpenBabel ，导入SMILES，这个开启更多文件导入导出 vue是对应的api是那个呀

2. 加载的.mol数据如何追加到编辑框中呢,现在是直接覆盖了。
`<template>

	<div class="container">
		<button @click="test">aaa</button>
		<button @click="test1">bbb</button>
		<div class="content">
			<composer class="left" id="composer" ref="composer" vue-predefined-setting="fullFunc" v-model="chemObj"
				v-model:vueSelection="selection" v-model:vueHotTrackedObjs="hotTrackedObjs"
				@userModificationDone="onComposerUserModificationDone" v-model:vueShowObjInspector="showObjInspector"
				v-model:vueShowIssueInspector="showIssueInspector"></composer>
			<viewer class="right" id="viewer" ref="viewer" vue-predefined-setting="fullFunc" :vue-chem-obj="chemObj"
				:vue-render-type="3"></viewer>
		</div>
	</div>
</template>

<script>
import 'kekule'
import 'kekule/theme'
import * as THREE from 'three'
Kekule.externalResourceManager.register('three.js', THREE);
import { Components } from 'kekule-vue'
console.log(Kekule.Render, 'Kekule.Render.rendererType.R3D')

let Viewer = Components.Viewer;
let Composer = Components.Composer;

var N = Kekule.ChemWidget.ComponentWidgetNames;
var C = Kekule.Editor.ObjModifier.Category;
console.log(N, C, 'NC')

export default {
	name: "composerAndViewer",
	components: { Viewer, Composer },
	data() {
		return {
			'chemObj': undefined,
			selection: undefined,
			hotTrackedObjs: undefined,

			showObjInspector: undefined,
			showIssueInspector: undefined
		}
	},
	mounted() {
		console.log(this.$refs.composer.getWidget(), )
	},
	methods: {
		test() {
			this.$refs.composer.getWidget()
				.setEnableOperHistory(true)
				.setEnableLoadNewFile(true)
				.setEnableCreateNewDoc(true)
				.setAllowCreateNewChild(true)
				.setCommonToolButtons(["newDoc",
					"loadData",
					"saveData",
					"undo",
					"redo",
					"copy",
					"cut",
					"paste",
					"zoomIn",
					"zoomOut",
					"config",
					"objInspector", {
						"name": "commonCustom1",
						// use your own Action class here to do some concrete work
						"actionClass": Class.create(Kekule.Editor.ActionOnComposerAdv, {}),
						"hint": "Custom action 1"
					},])   // create all default common tool buttons
				.setChemToolButtons(['manipulate', 'erase', 'bond', 'atom', 'formula',
					'ring', 'charge', 'glyph', 'textAndImage'])   // create all default chem tool buttons
				.setStyleToolComponentNames(['fontName', 'fontSize', 'color',
					'textDirection', 'textAlign']);  // create all default style components
		},
		test1() {
			let that = this
			var resId = 'url(#molResExternalLink)';
			Kekule.IO.loadResourceData('url(#molResExternalLink)', function (mol, success) {
				if (success) {
					that.chemObj = mol
					console.log('Loading from ' + resId + ' Successful');
					console.log(mol, success)
				}
				else {
					console.log('Loading from ' + resId + ' Failed');
				}
			});
		},
		onComposerUserModificationDone() {
			// console.log(this.$refs.composer.getWidget())
			this.$refs.viewer.getWidget().requestRepaint();
		}
	}
}
</script>

<style scoped>
.container {
	width: 100vw;
	height: 100vh;
	display: flex;
	flex-direction: column;
	align-items: flex-start;
}

.container .content {
	width: 100%;
	flex: 1;
	display: flex;
}

.container .left,
.container .right {
	flex: 1;
}
</style>`

**Comment by summerooo** [comment]
> 不需要做什么特别处理啊，import kekule与kekule-vue后，程序会自动检测浏览器语言。如果发现是中文环境，会自动使用汉语资源的：
> 
> ```
> <script setup>
> import 'kekule';
> import 'kekule/theme';
> import { Components } from 'kekule-vue';
> 
> const Composer = Components.Composer;
> </script>
> 
> <template>
>   <section>
>     <Composer></Composer>
>   </section>
> </template>
> ```
> 
> 请参考附件中的简单示例： [kekule-vue-vite.zip](https://github.com/user-attachments/files/16824787/kekule-vue-vite.zip)

你好老哥，以下是遇到的疑惑。

1. https://partridgejiang.github.io/Kekule.js/demos/items/chemViewer/chemViewer2D.html
导出OpenBabel ，导入SMILES，这个开启更多文件导入导出 vue是对应的api是那个呀

2. 加载的.mol数据如何追加到编辑框中呢,现在是直接覆盖了。


以下是我的vue代码

<template>

	<div class="container">
		<button @click="test">aaa</button>
		<button @click="test1">bbb</button>
		<div class="content">
			<composer class="left" id="composer" ref="composer" vue-predefined-setting="fullFunc" v-model="chemObj"
				v-model:vueSelection="selection" v-model:vueHotTrackedObjs="hotTrackedObjs"
				@userModificationDone="onComposerUserModificationDone" v-model:vueShowObjInspector="showObjInspector"
				v-model:vueShowIssueInspector="showIssueInspector"></composer>
			<viewer class="right" id="viewer" ref="viewer" vue-predefined-setting="fullFunc" :vue-chem-obj="chemObj"
				:vue-render-type="3"></viewer>
		</div>
	</div>
</template>

<script>
import 'kekule'
import 'kekule/theme'
import * as THREE from 'three'
Kekule.externalResourceManager.register('three.js', THREE);
import { Components } from 'kekule-vue'
console.log(Kekule.Render, 'Kekule.Render.rendererType.R3D')

let Viewer = Components.Viewer;
let Composer = Components.Composer;

var N = Kekule.ChemWidget.ComponentWidgetNames;
var C = Kekule.Editor.ObjModifier.Category;
console.log(N, C, 'NC')

export default {
	name: "composerAndViewer",
	components: { Viewer, Composer },
	data() {
		return {
			'chemObj': undefined,
			selection: undefined,
			hotTrackedObjs: undefined,

			showObjInspector: undefined,
			showIssueInspector: undefined
		}
	},
	mounted() {
		console.log(this.$refs.composer.getWidget(), )
	},
	methods: {
		test() {
			this.$refs.composer.getWidget()
				.setEnableOperHistory(true)
				.setEnableLoadNewFile(true)
				.setEnableCreateNewDoc(true)
				.setAllowCreateNewChild(true)
				.setCommonToolButtons(["newDoc",
					"loadData",
					"saveData",
					"undo",
					"redo",
					"copy",
					"cut",
					"paste",
					"zoomIn",
					"zoomOut",
					"config",
					"objInspector", {
						"name": "commonCustom1",
						// use your own Action class here to do some concrete work
						"actionClass": Class.create(Kekule.Editor.ActionOnComposerAdv, {}),
						"hint": "Custom action 1"
					},])   // create all default common tool buttons
				.setChemToolButtons(['manipulate', 'erase', 'bond', 'atom', 'formula',
					'ring', 'charge', 'glyph', 'textAndImage'])   // create all default chem tool buttons
				.setStyleToolComponentNames(['fontName', 'fontSize', 'color',
					'textDirection', 'textAlign']);  // create all default style components
		},
		test1() {
			let that = this
			var resId = 'url(#molResExternalLink)';
			Kekule.IO.loadResourceData('url(#molResExternalLink)', function (mol, success) {
				if (success) {
					that.chemObj = mol
					console.log('Loading from ' + resId + ' Successful');
					console.log(mol, success)
				}
				else {
					console.log('Loading from ' + resId + ' Failed');
				}
			});
		},
		onComposerUserModificationDone() {
			// console.log(this.$refs.composer.getWidget())
			this.$refs.viewer.getWidget().requestRepaint();
		}
	}
}
</script>

<style scoped>
.container {
	width: 100vw;
	height: 100vh;
	display: flex;
	flex-direction: column;
	align-items: flex-start;
}

.container .content {
	width: 100%;
	flex: 1;
	display: flex;
}

.container .left,
.container .right {
	flex: 1;
}
</style>

**Comment by partridgejiang** [comment]
1. OpenBabel需要在运行时动态加载额外的wasm文件（以及与之配合的一系列js文件），而这些文件一般不会被自动化工具打包，需要额外处理一下。这些文件位于 ```node_modules/Kekule/dist/extra/``` 中，请将```openbabel.*```以及```kekule.worker.obStructureGenerator.js```复制到您服务器中单独的目录下，并通过如下代码为Kekule.js设置路径信息：
```js
import 'kekule';
// ...
Kekule.environment.setEnvVar("openbabel.path", "https://your.domain/openbabel-path/");
```
（在附件的示例中，这组文件位于/public/openbabel/目录下，打包后位于/dist/openbabel/目录中。当然也可以采用其它的位置，只要通过```setEnvVar```设置好路径即可。）

这之后，就可以使用OpenBabel的功能了，包括读入SMILES：
```js
Kekule.OpenBabel.enable((error) => {
    if (error) {
      console.error(error.message);
    } else {
      const smiles = 'c1ccccc1';
      window.composer = composerWidget.value.getWidget();
      composerWidget.value.getWidget().loadFromData(
          smiles,
          null,
          null,
          Kekule.IO.DataFormat.SMILES
      );
      console.log('SMILES1 Loaded');
    }
});
```

2. 向编辑器追加新的数据，可以使用如下的代码，详见附件示例中```appendMolData```函数。
```js
Kekule.Editor.ActionOperUtils.addObjectsToChemSpaceEditor(composer.editor, [mol], {'autoSelect': true});
```

3. 向编辑器追加的自定义按钮，最简单的设置响应点击事件的方式是提供一个特殊的```#execute```字段，相应按钮对应的```execute```事件：
```js
composer.setCommonToolButtons([
      ... composer.getDefaultCommonToolBarButtons(),
      {
        name: "custom1",
        hint: "Custom 1",
        '#execute': () => {   // executed when button being activated
          alert('Custom 1');
        }
      }
]);
```
同样，具体可以参见附件示例中的相关代码。
[kekule-vue-vite.zip](https://github.com/user-attachments/files/16844456/kekule-vue-vite.zip)

**Comment by summerooo** [comment]
> 1. OpenBabel需要在运行时动态加载额外的wasm文件（以及与之配合的一系列js文件），而这些文件一般不会被自动化工具打包，需要额外处理一下。这些文件位于 `node_modules/Kekule/dist/extra/` 中，请将`openbabel.*`以及`kekule.worker.obStructureGenerator.js`复制到您服务器中单独的目录下，并通过如下代码为Kekule.js设置路径信息：
> 
> ```js
> import 'kekule';
> // ...
> Kekule.environment.setEnvVar("openbabel.path", "https://your.domain/openbabel-path/");
> ```
> 
> （在附件的示例中，这组文件位于/public/openbabel/目录下，打包后位于/dist/openbabel/目录中。当然也可以采用其它的位置，只要通过`setEnvVar`设置好路径即可。）
> 
> 这之后，就可以使用OpenBabel的功能了，包括读入SMILES：
> 
> ```js
> Kekule.OpenBabel.enable((error) => {
>     if (error) {
>       console.error(error.message);
>     } else {
>       const smiles = 'c1ccccc1';
>       window.composer = composerWidget.value.getWidget();
>       composerWidget.value.getWidget().loadFromData(
>           smiles,
>           null,
>           null,
>           Kekule.IO.DataFormat.SMILES
>       );
>       console.log('SMILES1 Loaded');
>     }
> });
> ```
> 
> 2. 向编辑器追加新的数据，可以使用如下的代码，详见附件示例中`appendMolData`函数。
> 
> ```js
> Kekule.Editor.ActionOperUtils.addObjectsToChemSpaceEditor(composer.editor, [mol], {'autoSelect': true});
> ```
> 
> 3. 向编辑器追加的自定义按钮，最简单的设置响应点击事件的方式是提供一个特殊的`#execute`字段，相应按钮对应的`execute`事件：
> 
> ```js
> composer.setCommonToolButtons([
>       ... composer.getDefaultCommonToolBarButtons(),
>       {
>         name: "custom1",
>         hint: "Custom 1",
>         '#execute': () => {   // executed when button being activated
>           alert('Custom 1');
>         }
>       }
> ]);
> ```
> 
> 同样，具体可以参见附件示例中的相关代码。 [kekule-vue-vite.zip](https://github.com/user-attachments/files/16844456/kekule-vue-vite.zip)


十分感谢老哥,不过话说相关文档可以去哪里看呀？

**Comment by partridgejiang** [comment]
https://partridgejiang.github.io/Kekule.js/ 的tutorial里有一些最为常用功能的介绍，进而可以参阅 demos 里的源码。遇上困难当然也欢迎在 issues 里提出，:)。

**Comment by summerooo** [comment]
> https://partridgejiang.github.io/Kekule.js/ 的tutorial里有一些最为常用功能的介绍，进而可以参阅 demos 里的源码。遇上困难当然也欢迎在 issues 里提出，:)。

好嘞，再次感谢老哥。
