### ISSUE TITLE
I cannot load the resource in MOL2000 format through Kekule.IO.loadResourceData  

### ISSUE THREAD

**Issue by hyh6411** [partridgejiang/Kekule.js#325]
Docs: http://partridgejiang.github.io/Kekule.js/documents/tutorial/content/molIO.html#example

I copied the same code for loading MOL2000 resources as described in the official documentation on Doem, but it just couldn't run successfully in my environment.  

When running to Kekule.IO.loadResourceData, an error will be reported: Format error! But this resource was copied from the official website.  

code: 

  <script src="https://unpkg.com/@rdkit/rdkit/dist/RDKit_minimal.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r127/three.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/kekule/dist/themes/default/kekule.css" />
  <script src="https://cdn.jsdelivr.net/npm/kekule/dist/kekule.min.js"></script>

  <script id="molResInsideElem" type="chemical/x-mdl-molfile">

    CDK    9/19/06,14:29
  
   12 12  0  0  0  0  0  0  0  0999 V2000
    415.0000  974.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    383.8231  992.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    383.8231 1028.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    415.0000 1046.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    446.1769 1028.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    446.1769  992.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    352.6462 1046.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    352.6462 1082.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    352.6462  974.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    415.0000  938.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    477.3538  974.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    477.3538 1046.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1  2  1  0  0  0  0
    2  3  1  0  0  0  0
    3  4  1  0  0  0  0
    4  5  1  0  0  0  0
    5  6  1  0  0  0  0
    6  1  1  0  0  0  0
    3  7  1  1  0  0  0
    7  8  1  0  0  0  0
    2  9  1  6  0  0  0
    1 10  1  1  0  0  0
    6 11  1  1  0  0  0
    5 12  1  0  0  0  0
  M  END
    
  </script>

setTimeout(() => {
      var resId = 'url(#molResInsideElem)';
      Kekule.IO.loadResourceData(resId, function(mol, success) { // here will be error....
        if (success) {
          console.log('Loading from ' + resId + ' Successful');
          molRender3D(mol);
        } else {
          console.log('Loading from ' + resId + ' Failed');
        }
      });
    }, 1000)

**Comment by partridgejiang** [comment]
Hi @hyh6411, MOL2000 is a strict data format. Line breaks, blank lines and even spaces make sense in the data.  You should not merge all data into one line. So the proper code should be:
```html
<script id="molResInsideElem" type="chemical/x-mdl-molfile">

  CDK    9/19/06,14:29

 12 12  0  0  0  0  0  0  0  0999 V2000
  415.0000  974.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  383.8231  992.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  383.8231 1028.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  415.0000 1046.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  446.1769 1028.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  446.1769  992.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  ...
</script>
```

**Comment by hyh6411** [comment]
![image](https://github.com/user-attachments/assets/fcf314af-1f6c-41bd-8549-4511b0876fe5)

我是这样写的，只是git给我的格式弄乱了，为了防止tab键会影响MOL2000资源，我这次还特地测了上图中这种情况，最后还是不行，关于我加载MOL2000的代码在下面：

`function MOL2000ToKekule(MOL2000) {
    console.log(MOL2000, '=========MOL2000==========>')

    // MOL2000 转 kekule
    const scriptId = 'molResInsideElem'
    // let kekule_script = '<script id="' + scriptId + '" type="chemical/x-mdl-molfile">' + MOL2000 + '<\/script>'
    // 将 kekule_script 插入到 body 中
    // document.body.insertAdjacentHTML('beforeend', kekule_script)
    // 等待 kekule 加载完成
    // window.addEventListener('kekuleReady', function() {
    //   console.log('kekule 加载完成')
    // })
    setTimeout(() => {
      var resId = 'url(#molResInsideElem)';
      console.log(document.getElementById(scriptId), '===========>')
      Kekule.IO.loadResourceData(resId, function(mol, success) {
        if (success) {
          console.log('Loading from ' + resId + ' Successful');
          molRender3D(mol);
        } else {
          console.log('Loading from ' + resId + ' Failed');
        }
      });
    }, 1000)
  }`

**Comment by partridgejiang** [comment]
留神在```  CDK    9/19/06,14:29```之前应该有个空行，这一行是MOL2000的分子名称行，可以留空，但不能没有这行。

**Comment by hyh6411** [comment]
好的感谢，问题被解决了，我发现由RDkit生成的MOL2000第一行也没有空行，需要手动拼上空行就能用了：

RDkit生成MOL2000
```
function RDKitSmilesToMOL2000(smiles) {
  var mol = RDKitModule.get_mol(smiles);
  return mol.get_kekule_form();
}
```

MOL2000转为kekule
```
function MOL2000ToKekule(MOL2000) {
  const scriptId = 'molResInsideElem'

  // 生成MOL2000资源
  let kekule_script = '<script id="' + scriptId + '" type="chemical/x-mdl-molfile">' + '\n' + MOL2000 + '<\/script>'

  // 将 kekule_script 插入到 body 中
  document.body.insertAdjacentHTML('beforeend', kekule_script)

  // 加载MOL2000资源
  setTimeout(() => {
    var resId = 'url(#molResInsideElem)';
    console.log(document.getElementById(scriptId), '===========>')
    Kekule.IO.loadResourceData(resId, function(mol, success) {
      if (success) {
        console.log('Loading from ' + resId + ' Successful');
        molRender3DView(mol);
      } else {
        console.log('Loading from ' + resId + ' Failed');
      }
    });
  }, 1000)
}
```

**Comment by partridgejiang** [comment]
这儿要载入一个MOL2000格式的字符串其实不用这么兜圈儿的，底下的代码就可以：

```js
const molData = RDKitSmilesToMOL2000(smiles)
const mol = Kekule.IO.loadFormatData(molData, Kekule.IO.DataFormat.MOL);
if (mol)
  molRender3DView(mol);
```
