### ISSUE TITLE
请问在3D视图中要如何设置原子的颜色和打光？

### ISSUE THREAD

**Issue by hyh6411** [partridgejiang/Kekule.js#328]
UI说颜色太暗了。。。

翻了下官网的文档，没有找到对应的配置项

![image](https://github.com/user-attachments/assets/c6c7f102-13e5-4754-a2e7-557b7abc5b7c)

**Comment by partridgejiang** [comment]
这个Three.js渲染过暗的问题应该在v1.0.1里解决了（commit #8c34d4b2 与 #567fe822），麻烦先检查一下当前使用的Kekule的版本，看看 ```Kekule.VERSION``` 是否是 1.0.1？另外也可以检查一下Three.js的版本（```THREE.REVISION```）。

**Comment by hyh6411** [comment]
![image](https://github.com/user-attachments/assets/0c363d74-21d3-4d2d-93c2-ff79fa2cf915)
![image](https://github.com/user-attachments/assets/34e154d0-2a7a-477d-b774-648506bb3588)

我的版本是1.0.1应该没有问题吧，是不是我的使用方式的问题：

```
this.viewer3D = new Kekule.ChemWidget.Viewer3D(this.$refs.kekule3DViewerRef);
this.viewer3D.setDimension(this.width, this.height);
this.viewer3D.setBackgroundColor('transparent');
this.viewer3D.setChemObj(mol);
```

**Comment by partridgejiang** [comment]
我这儿知道原因了，Three.js最近的版本里去除了WebGLRenderer对象的useLegacyLights标志，导致光源强度设置出了问题。回头我来解决这个问题，目前可以用以下的代码进行临时修正：
```js
var threeObjs = this.viewer3D.getDrawContext().scene.children;
threeObjs.forEach(o => {
	if (o.type === 'DirectionalLight' || o.type === 'AmbientLight')
		o.intensity *= Math.PI;
});
this.viewer3D.repaint();
```

**Comment by hyh6411** [comment]
好的，非常感谢
