### ISSUE TITLE
Show atom colors in molecule representation

### ISSUE THREAD

**Issue by gbayarri** [partridgejiang/Kekule.js#50]
Hi, I have a simple representation:

```
function showMolecule2D(mol) {
  Kekule.Widget.getWidgetById('chemViewer2D').setChemObj(mol);
  Kekule.Widget.getWidgetById('chemViewer2D').setToolButtons(['molDisplayType', 'zoomIn', 'zoomOut']);
}
```

The output for this function is a molecule representation:

![screenshot](https://user-images.githubusercontent.com/19928100/38876055-042e0a90-425c-11e8-9ac6-2822333f5565.png)

But the Nitrogens and Oxygens of this molecule have not the typical blue / red color as in the kekule composer. Is there any way to pass a parameter or call a method to do that in my code?

Thanks.

**Comment by partridgejiang** [comment]
You can use the following code before the loading process to render atoms with different color:
```js
var viewer = Kekule.Widget.getWidgetById('chemViewer2D');
viewer.getRenderConfigs().getColorConfigs().setUseAtomSpecifiedColor(true);
// ......
viewer.setChemObj(mol);
```

**Comment by gbayarri** [comment]
Hi, @partridgejiang it works perfectly.

Thank you!
