### ISSUE TITLE
Stereoisomer matching with multiple stereo bonds

### ISSUE THREAD

**Issue by MrDarkHorse** [partridgejiang/Kekule.js#81]
Found some weird scenarios, best shown with pictures.  In my case, I'm comparing structures with 2 stereo bonds, and I'm really testing for isometry here.

First case, same structure, it correctly matches them:
![screen shot 2018-09-26 at 1 51 14 pm](https://user-images.githubusercontent.com/9271182/46102596-54fd3100-c194-11e8-9521-7e5a7e68aef9.png)

Second case, I drop the Oxygen to the other side, and again, it correctly knows that these structures no longer match:
![screen shot 2018-09-26 at 1 51 28 pm](https://user-images.githubusercontent.com/9271182/46102682-8aa21a00-c194-11e8-905c-1de60c5522f7.png)

Then it starts getting weird.

Third case, I drop the Nitrogen below the left bond, but it still thinks they match
![screen shot 2018-09-26 at 1 53 54 pm](https://user-images.githubusercontent.com/9271182/46102759-b3c2aa80-c194-11e8-84b7-74516bdbd498.png)

There are other variants as well.

Fourth case, I pull the Chlorine above the bond on the right, and it still thinks they match:
![screen shot 2018-09-26 at 1 52 50 pm](https://user-images.githubusercontent.com/9271182/46102799-cc32c500-c194-11e8-9734-28d12fdc4437.png)

Another version of the previous:
![screen shot 2018-09-26 at 1 52 41 pm](https://user-images.githubusercontent.com/9271182/46102838-e4a2df80-c194-11e8-819c-d005000475fa.png)

Seems like something in the parity calculation breaks down.  Right?

**Comment by MrDarkHorse** [comment]
Any thoughts on this?

**Comment by partridgejiang** [comment]
@MrDarkHorse Thanks a lot for the feedback. In current bond stereo detection code, it is assumed that the end atoms/groups should be on different side of the bond line. The error may occur when two end groups are moved to the same side of bond as shown in your figures. This issue should be fixed soon.

**Comment by MrDarkHorse** [comment]
Thanks!  I know these are kind of ambiguous scenarios.  In our situation, since we use this for teaching purposes, we would prefer that ambiguous defaults to non-matching.  Thank you so much for your help!

**Comment by partridgejiang** [comment]
@MrDarkHorse The issue has been fixed, please check the latest release files, :).

**Comment by MrDarkHorse** [comment]
Thank you for fixing this!

One more ambiguous case I'm trying to deal with is if we are trying to match an ambiguous linear bond.  Again, this is weird, but right now this is matching, and I was hoping that in this case it would default to not matching.  I had a solution for this using the old method, but I haven't been able to sort it out using the new method.

![screen shot 2018-10-23 at 1 04 15 pm](https://user-images.githubusercontent.com/9271182/47381015-70405b00-d6c4-11e8-982a-6702fe8054f6.png)
![screen shot 2018-10-23 at 1 04 02 pm](https://user-images.githubusercontent.com/9271182/47381016-70405b00-d6c4-11e8-9e70-0a2e6deff1a7.png)

**Comment by MrDarkHorse** [comment]
Wait!  I actually have a solution for this.  I could make a pull request for it if it's something others are interested in having.

**Comment by MrDarkHorse** [comment]
adding the following lines in _calcParityOfCoordPairs:

`var axisAngle = Math.atan2(axisVector.y, axisVector.x);

        var rightAxisVector = CU.substract(c1, a1);  // vector of bond
        var leftAxisVector = CU.substract(b1, c2);  // vector of bond
        var rightAxisAngle = Math.atan2(rightAxisVector.y, rightAxisVector.x);
        var leftAxisAngle = Math.atan2(leftAxisVector.y, leftAxisVector.x);

        var threshold = 1e-2; // CU.getDistance(c2, c1) / 1e3;
        var leftDiff = Math.abs(axisAngle - leftAxisAngle);
        var rightDiff = Math.abs(axisAngle - rightAxisAngle);

		// if there is an linearly drawn bond angle, the stereo parity is UNKNOWN
        if (leftDiff < threshold || rightDiff < threshold) {
            return SP.UNKNOWN;
		}`

**Comment by partridgejiang** [comment]
@MrDarkHorse The liner bond issue is now fixed. Please check the latest release files.
