### ISSUE TITLE
Bulk setChemObj in composer

### ISSUE THREAD

**Issue by robertf224** [partridgejiang/Kekule.js#84]
I can't figure out how to add multiple molecules.  Using `setChemObj` [as described here](http://partridgejiang.github.io/Kekule.js/documents/tutorial/content/composer.html#loading-and-retrieving-molecules-in-composer) in sequence doesn't work because each call overrides the previous.  Is there some way I can add multiple molecules using the current APIs?

**Comment by partridgejiang** [comment]
The root object in an composer is actually an instance of Kekule.ChemDocument (when calling ```composer.setChemObj(molecule)```, the molecule is actually inserted into this document), so the following code may be used to add multiple molecules to composer:
```js
var molecules = [mol1, mol2, mol3];
var chemDoc = composer.getChemObj();
molecules.forEach(function(mol){
  chemDoc.appendChild(mol);
});
```

**Comment by robertf224** [comment]
awesome thanks!
