### ISSUE TITLE
Documention: Kekule.ChemWidget.Viewer 

### ISSUE THREAD

**Issue by jvansan** [partridgejiang/Kekule.js#87]
In many places in the documentation, there is a reference to a page for `Kekule.ChemWidget.Viewer`.
For instance: http://partridgejiang.github.io/Kekule.js/documents/api/chemWidget/Kekule.ChemWidget.Viewer2D.html 

It says that Viewer2D extends Viewer, however, there is not documentation for Viewer.

**Comment by partridgejiang** [comment]
Thanks a lot for the reminding. The old API documents are outdated and are now updated. The document of class Viewer can be found at https://partridgejiang.github.io/Kekule.js/documents/api/chemWidget/Kekule.ChemWidget.Viewer.html.

**Comment by jvansan** [comment]
Great, thanks for resolving!
